tutme/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.conf import settings
from django.conf.urls.static import static

from courses.views import HomeView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^course/', include('courses.urls')),
    url(r'^user/', include('users.urls')),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^$', HomeView.as_view(), name='home'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.conf.urls import url

from .views import LoginFormView, ResetPasswordFormView, ResetPasswordUpdateView, RegisterFormView, UserUpdateView, UserDetailView, ActivateView, LogoutView

urlpatterns = [
		url(r'^login/$', LoginFormView.as_view(), name='login'),
		url(r'^logout/$', LogoutView.as_view(), name='logout'),
		url(r'^register/$', RegisterFormView.as_view(), name='register'),
		url(r'^profile/$', UserDetailView.as_view(), name='profile'),
		url(r'^profile/edit/$', UserUpdateView.as_view(), name='profile-edit'),
		url(r'^activate/(?P<token>[\w-]+)/$', ActivateView.as_view(), name='activate'),
		url(r'^reset-password/$', ResetPasswordFormView.as_view(), name='reset-password'),
		url(r'^reset-password/(?P<token>[\w-]+)/$', ResetPasswordUpdateView.as_view(), name='reset-password-link'),
		url(r'^$', UserDetailView.as_view(), name='profile2'),
]

courses/models.py
from django.db import models
from django.db.models.query import QuerySet
from ckeditor_uploader.fields import RichTextUploadingField
from datetime import datetime
from django.utils.timezone import now
from django.template.defaultfilters import slugify

# Create your models here.
from django.contrib.auth import get_user_model
from django.conf import settings

class CustomQuerySetManager(models.Manager):
	def __getattr__(self, attr, *args):
		try:
			return getattr(self.__class__, attr, *args)
		except AttributeError:
			if attr.startswith('__') and attr.endswith('__'):
				raise
			return getattr(self.get_query_set(), attr, *args)

	def get_query_set(self):
		return self.model.QuerySet(self.model, using=self._db)

class Course(models.Model):
	name 		= models.CharField(max_length=128, blank=False, null=False, verbose_name='Nazwa')
	slug 		= models.SlugField(blank=True, null=True, verbose_name='Slug')
	description = models.CharField(max_length=255, verbose_name='Opis')
	password 	= models.CharField(max_length=16, blank=True, null=True, verbose_name='Hasło')
	cover 		= models.ImageField(upload_to='coures/covers/', blank=True, null=True, verbose_name='Okładka')

	updated 	= models.DateTimeField(auto_now=True, verbose_name='Modyfikowano')
	created 	= models.DateTimeField(auto_now_add=True, verbose_name='Utworzono')

	objects 	= CustomQuerySetManager()

	class Meta:
		verbose_name = 'Kurs'
		verbose_name_plural = '1. Kursy'

	def __str__(self):
		return self.name

	def save(self, *args, **kwargs):
		self.slug = slugify(self.name)
		super(Course, self).save(*args, **kwargs)

	def get_max_points(self):
		lectures = self.course_lecture.all()

		max_points = 0
		for lecture in lectures:
			max_points += lecture.points_max

		return max_points


	class QuerySet(QuerySet):
		def registered_on_user(self, user):
			return self.filter(user_courses__user=user)

class CustomLectureManager(models.Manager):
	def get_queryset(self):
		return super(CustomLectureManager, self).get_queryset().filter(active_time__gte=now())

class Lecture(models.Model):
	name 			= models.CharField(max_length=128, blank=False, null=False, verbose_name='Nazwa')
	slug 			= models.SlugField(blank=True, null=True, verbose_name='Slug')
	description 	= models.CharField(max_length=255, verbose_name='Opis')

	password 		= models.CharField(max_length=32, blank=True, null=True, verbose_name='Hasło')
	active_time 	= models.DateTimeField(default=datetime(2018, 1, 15, 12, 00), verbose_name='Aktywna do')

	file 			= models.FileField(upload_to='uploads/courses/files/', blank=True, null=True, verbose_name='Plik do zajęc')

	points_max 		= models.PositiveSmallIntegerField(default=10, blank=False, null=False, verbose_name='Max. pkt. za zajęcia')

	course 			= models.ForeignKey('Course', related_name='course_lecture', on_delete=models.CASCADE, verbose_name='Kurs')

	updated 		= models.DateTimeField(auto_now=True, verbose_name='Modyfikowano')
	created 		= models.DateTimeField(auto_now_add=True, verbose_name='Utworzono')

	objects 		= models.Manager()
	active_objects 	= CustomLectureManager()

	class Meta:
		verbose_name = 'Zajęcia'
		verbose_name_plural = '2. Zajęcia'

	def __str__(self):
		return self.name

	def is_active(self):
		if self.active_time >= now():
			return True
		else:
			return False
	is_active.short_description = 'Aktywny'

	def save(self, *args, **kwargs):
		self.slug = slugify(self.name)
		super(Lecture, self).save(*args, **kwargs)


class Page(models.Model):
	number 	= models.PositiveSmallIntegerField(blank=False, null=False, verbose_name='Numer strony')
	content = RichTextUploadingField(blank=False, null=False, verbose_name='Treść')

	lecture = models.ForeignKey('Lecture', related_name='pages', on_delete=models.CASCADE, verbose_name='Zajęcia')

	updated = models.DateTimeField(auto_now=True, verbose_name='Modyfikowano')
	created = models.DateTimeField(auto_now_add=True, verbose_name='Utworzono')

	class Meta:
		verbose_name = 'Strona zajęć'
		verbose_name_plural = '3. Strony zajęć'

	def __str__(self):
		return self.lecture.name + '(str. ' + str(self.number) + ')'

	def get_course(self):
		return self.lecture.course.name


class Task(models.Model):
	number 		= models.CharField(max_length=8, blank=False, null=False,  verbose_name='Numer')
	content		= models.CharField(max_length=255, blank=False, null=False,  verbose_name='Treść')
	lecture 	= models.ForeignKey(Lecture, related_name='task', on_delete=models.CASCADE,  verbose_name='Zajęcia')

	class Meta:
		verbose_name = 'Zadanie'
		verbose_name_plural = '4. Zadania'

	def __str__(self):
		return self.number


UT_PENDING 			= 'P'
UT_SENDED 			= 'S'
UT_APPROVED 		= 'A'
UT_DENIED 			= 'D'

USER_TASK_STATUS = (
		(UT_PENDING, 'Oczekuje'),
		(UT_SENDED, 'Przesłano'),
		(UT_APPROVED, 'Zaakceptowano'),
		(UT_DENIED, 'Odrzucono'),
	)

class UserTaskDetail(models.Model):
	task 	= models.ForeignKey(Task, related_name='user_task', on_delete=models.CASCADE, blank=True, null=True, verbose_name='Zadanie')
	user 	= models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name='Użytkownik')

	result 	= models.TextField(blank=False, null=True, verbose_name='Wynik')
	status 	= models.CharField(choices=USER_TASK_STATUS, max_length=1, default=UT_PENDING, blank=False, null=False, verbose_name='Status')

	updated = models.DateTimeField(auto_now=True, verbose_name='Modyfikowano')
	created = models.DateTimeField(auto_now_add=True, verbose_name='Utworzono')

	class Meta:
		verbose_name = 'Zadanie użytkownika'
		verbose_name_plural = '5. Zadania użytkowników'

	def get_lecture(self):
		return self.task.lecture
	get_lecture.short_description = 'Zajęcia'

users/views.py
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import authenticate, get_user_model, login, logout
from django.contrib.auth.mixins import LoginRequiredMixin
# from django.contrib.auth.models import User
from django.core.mail import EmailMultiAlternatives
from django.core.urlresolvers import reverse
from django.shortcuts import render, redirect
from django.template import Context
from django.template.loader import get_template
from django.views import View
from django.views.generic.detail import DetailView
from django.views.generic.edit import FormView, CreateView, UpdateView
# Create your views here.

from courses.models import Course
from .forms import LoginForm, RegisterForm, ResetPasswordForm, UserResetPasswordForm
from .models import UserCourseDetail, UserLectureDetail
from .utils import generate_token
from .messages import USERS_MESSAGES

class LogoutRequiredMixin(View):
	def dispatch(self, request, *args, **kwargs):
		if request.user.is_authenticated():
			return redirect('/')
		return super(LogoutRequiredMixin, self).dispatch(request, *args, **kwargs)

class CustomLoginActivateRequiredMixin(View):
	def dispatch(self, request, *args, **kwargs):
		if request.user.is_authenticated():
			user = request.user
			if user.profile_is_complete() or user.is_staff:
				return super(CustomLoginActivateRequiredMixin, self).dispatch(request, *args, **kwargs)
			else:
				messages.add_message(request, messages.WARNING, USERS_MESSAGES['PROFILE_NOT_COMPLETE'])
				return redirect('profile-edit')
		else:
			messages.add_message(request, messages.WARNING, USERS_MESSAGES['LOGIN_REQUIRED'])
		return redirect('login')

class CustomLoginRequiredMixin(View):
	def dispatch(self, request, *args, **kwargs):
		if request.user.is_authenticated():
			return super(CustomLoginRequiredMixin, self).dispatch(request, *args, **kwargs)
		else:
			messages.add_message(request, messages.WARNING, USERS_MESSAGES['LOGIN_REQUIRED'])
		return redirect('login')
		

class RegisterFormView(LogoutRequiredMixin, FormView):
	form_class = RegisterForm
	# fields = ['first_name', 'last_name', 'email', 'password', ]
	template_name = 'users/register_form.html'
	success_url = '/'

	def post(self, request, *args, **kwargs):
		form = RegisterForm(request.POST or None)

		if form.is_valid():
			user_model = get_user_model()
			user = user_model.objects.create_user(email=form.cleaned_data['email'],
											password=form.cleaned_data['password1'],
										)

			token = generate_token()
			user.activation_token = token
			user.save()

			activation_link = "http://%s%s" % (settings.SITE_URL, reverse('activate', args=[token]))

			plaintext = get_template('emails/user_activation.txt')
			htmly     = get_template('emails/user_activation.html')

			d = {
				'activation_link'	: activation_link,
				'user_name' 		: form.cleaned_data['email'],
				}

			subject 	= 'Aktywacja konta na platformie tutMe'
			from_email 	= 'admin@tutme.pl'
			to 			= form.cleaned_data['email']

			text_content = plaintext.render(d)
			html_content = htmly.render(d)
			msg = EmailMultiAlternatives(subject, text_content, from_email, [to])
			msg.attach_alternative(html_content, "text/html")
			msg.send()

			messages.add_message(request, messages.SUCCESS, USERS_MESSAGES['REGISTRATION_SUCCESS'])
			return redirect('login')

		else:
			messages.add_message(request, messages.ERROR, USERS_MESSAGES['REGISTRATION_FAIL'])
			return self.render_to_response(self.get_context_data())


class LoginFormView(LogoutRequiredMixin, FormView):
	template_name = 'users/login_form.html'
	success_url = '/'
	form_class = LoginForm

	def post(self, request, *args, **kwargs):
		form = LoginForm(request.POST or None)
		if form.is_valid():
			email = form.cleaned_data['email']
			password = form.cleaned_data['password']

			get_user = get_user_model()

			try:
				user = get_user.objects.get(email=email)
			except:
				messages.add_message(request, messages.ERROR, USERS_MESSAGES['USER_LOGIN_NOT_FOUND'])
			else:
				if user.check_password(password):
					if user is not None:
						if user.is_active:
							login(request, user)
							messages.add_message(request, messages.INFO, USERS_MESSAGES['USER_LOGIN_SUCCESS'])
							return redirect('/')
						else:
							messages.add_message(request, messages.ERROR, USERS_MESSAGES['USER_NOT_ACTIVE'])
				else:
					messages.add_message(request, messages.ERROR, USERS_MESSAGES['USER_LOGIN_FAIL'])
		else:
			messages.add_message(request, messages.ERROR, USERS_MESSAGES['USER_LOGIN_ERROR'])
		return self.render_to_response(self.get_context_data())


class LogoutView(CustomLoginRequiredMixin, View):
	def get(self, request, *args, **kwargs):
		logout(request)
		messages.add_message(request, messages.INFO, USERS_MESSAGES['USER_LOGOUT'])
		return redirect('/')

class UserUpdateView(CustomLoginRequiredMixin, UpdateView):
	model = get_user_model()
	fields = ['first_name', 'last_name', 'index', 'group',]

	def get_success_url(self):
		return reverse('profile')
	
	def get_object(self):
		User = get_user_model()
		user = self.request.user
		obj = User.objects.get(pk=user.pk)
		return obj

	def form_valid(self, form):
		messages.add_message(self.request, messages.INFO, USERS_MESSAGES['USER_PROFILE_CHANGE_SUCCESS'])
		return super(UserUpdateView, self).form_valid(form)


class UserDetailView(CustomLoginRequiredMixin, DetailView):
	model = get_user_model()

	def get_object(self, *args, **kwargs):
		User = get_user_model()
		user = self.request.user
		return User.objects.get(pk=user.pk)

	def get_context_data(self, *args, **kwargs):
		user = self.request.user
		courses = UserCourseDetail.objects.filter(user=user).order_by('-pk')

		points = 0
		for course in courses:
			points += course.get_user_points()

		context = super(UserDetailView, self).get_context_data(*args, **kwargs)
		context['courses'] = courses

		return context


class ActivateView(LogoutRequiredMixin, View):
	def get(self, request, token, *args, **kwargs):
		try:
			user_model = get_user_model()
			user = user_model.objects.get(activation_token=token)
			user.is_active = True
			user.activation_token = None
			user.save()
			messages.add_message(request, messages.INFO, USERS_MESSAGES['USER_ACTIVATE_SUCCESS'])
		except:
			messages.add_message(request, messages.ERROR, USERS_MESSAGES['USER_ACTIVATE_ERROR'])
		return redirect('/')


class ResetPasswordFormView(LogoutRequiredMixin, FormView):
	template_name = 'users/reset_password_form.html'
	success_url = '/'
	form_class = ResetPasswordForm

	def post(self, request, *args, **kwargs):
		form =  ResetPasswordForm(request.POST or None)

		if form.is_valid():
			email = form.cleaned_data['email']
			get_user = get_user_model()

			try:
				user = get_user.objects.get(email=email)
			except:
				messages.add_message(request, messages.ERROR, USERS_MESSAGES['USER_LOGIN_NOT_FOUND'])
				return redirect('reset-password')

			# profile = Profile.objects.get(user=user)

			token = generate_token()

			user.reset_token = token
			user.save()

			reset_link = "http://%s%s" % (settings.SITE_URL, reverse('reset-password-link', args=[token]))

			plaintext = get_template('emails/user_reset_password.txt')
			htmly     = get_template('emails/user_reset_password.html')

			d = {
				'reset_link'	: reset_link,
				'user_name' 	: user.get_short_name(),
				}

			subject 	= 'Reset hasła na platformie tutMe'
			from_email 	= 'admin@tutme.pl'
			to 			= user.email

			text_content = plaintext.render(d)
			html_content = htmly.render(d)
			msg = EmailMultiAlternatives(subject, text_content, from_email, [to])
			msg.attach_alternative(html_content, "text/html")
			msg.send()

			messages.add_message(request, messages.INFO, USERS_MESSAGES['USER_REMIND_EMAIL_SENT'])

		return redirect('/')


class ResetPasswordUpdateView(LogoutRequiredMixin, UpdateView):
	model = get_user_model()
	form_class = UserResetPasswordForm
	template_name = 'users/reset_password_update.html'
	success_url = '/'

	def dispatch(self, request, token, *args, **kwargs):
			try:
				user_model = get_user_model()
				user = user_model.objects.get(reset_token=token)
			except:
				messages.add_message(request, messages.ERROR, USERS_MESSAGES['USER_RESET_PASSWORD_ERROR'])
				return redirect('/')
			else:
				return super(ResetPasswordUpdateView, self).dispatch(request, token, *args, **kwargs)
	
	def get_object(self):
			try:
				user_model = get_user_model()
				user = user_model.objects.get(reset_token=token)
				return user
			except:
				return None

	def post(self, request, token, *args, **kwargs):
		form = UserResetPasswordForm(request.POST or None)

		if form.is_valid():
			password = form.cleaned_data['password']
			password2 = form.cleaned_data['password2']

			user_model = get_user_model()
			user = user_model.objects.get(reset_token=token)
			user.set_password(password)
			user.reset_token = None
			user.save()

			messages.add_message(request, messages.INFO, USERS_MESSAGES['USER_RESET_PASSWORD_SUCCESS'])
		else:
			messages.add_message(request, messages.ERROR, USERS_MESSAGES['USER_RESET_PASSWORD_FAIL'])
			return redirect('reset-password-link', token=token)

		return redirect('login')

templates/users/announcement_list.html
{% extends '../base.html' %}

{% block main %}

	<hr class="hr-custom">

	<div class="row">
		<div class="col-md-8 mx-auto">
			<h2 class="featurette-heading">Najnowsze ogłoszenia</h2>
		</div>
	</div>

	<hr class="hr-custom">
	<div class="row">
		<div class="col-md-12">
			{% for news in object_list %}
				<div class="row news-list" id='a{{ news.pk }}'>
					<div class="col-3">
						<div class="news-link d-inline-block"><a href="{% url 'announcements' %}#a{{ news.pk }}">#</a></div>
						<div class="d-inline-block">{{ news.updated|date:"d.m.Y H:i" }}</div>
					</div>
					<div class="col-6">{{ news.text }}</div>
					<div class="col-3">{{ news.get_author }}</div>
				</div>
			{% endfor %}
		</div>
	</div>
{% endblock %}

templates/users/login_form.html
{% extends '../base.html' %}
{% load form_attrs %}

{% block main %}

    <hr class="hr-custom">

    <h2>Zaloguj się</h2>
    <h5>Nie pamiętasz hasła? <a href="{% url 'reset-password' %}">Resetuj hasło.</a></h5>
    <h5>Nie masz konta? <a href="{% url 'register' %}">Załóż nowe.</a></h5>

    <hr class="hr-custom">

    <div class="row">
        <div class="col-md-12">
            {% if form %}
                <form method="POST">
                    {% csrf_token %}
                    <div class="form-group row">
                        <label for="email" class="col-md-3 col-form-label">Email*:</label>
                        <div class="col-md-4">
                            {{ form.email|addatr:"class: form-control, id:email" }}
                            {% if form.email.errors %}
                                {% for error in form.email.errors %}
                                    <div class="invalid-feedback invalid-feedback-custom">{{ error }}</div>
                                {% endfor %}
                            {% endif %}
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="password" class="col-md-3 col-form-label">Hasło*:</label>
                        <div class="col-md-4">
                            {{ form.password|addatr:"class: form-control, id:password" }}
                            {% if form.password.errors %}
                                {% for error in form.password.errors %}
                                    <div class="invalid-feedback invalid-feedback-custom">{{ error }}</div>
                                {% endfor %}
                            {% endif %}
                        </div>
                    </div>
                    <div class="row">
                       <div class="col-md-7">
                            <div class="text-right">
                                <input type="submit" class="btn btn-outline-primary w-25" value="Zaloguj">
                            </div>
                        </div>
                    </div>
                </form>
            {% endif %}
        </div>
    </div>
{% endblock %}

templates/users/register_form.html
{% extends '../base.html' %}
{% load form_attrs %}

{% block main %}

    <hr class="hr-custom">

    <h2>Załóż nowe konto</h2>
    <h5>Posiadasz już konto? <a href="{% url 'login' %}">Zaloguj się.</a></h5>

    <hr class="hr-custom">

    <div class="row">
        <div class="col-md-12">
            {% if form %}
                <form method="POST">
                    {% csrf_token %}
                    <div class="form-group row">
                        <label for="email" class="col-md-3 col-form-label">Email*:</label>
                        <div class="col-md-4">
                            {{ form.email|addatr:"class: form-control, id:email" }}
                            {% if form.email.errors %}
                                {% for error in form.email.errors %}
                                    <div class="invalid-feedback invalid-feedback-custom">{{ error }}</div>
                                {% endfor %}
                            {% endif %}
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="password" class="col-md-3 col-form-label">Hasło*:</label>
                        <div class="col-md-4">
                            {{ form.password1|addatr:"class: form-control, id:password" }}
                            {% if form.password1.errors %}
                                {% for error in form.password1.errors %}
                                    <div class="invalid-feedback invalid-feedback-custom">{{ error }}</div>
                                {% endfor %}
                            {% endif %}
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="password2" class="col-md-3 col-form-label">Powtórz hasło*:</label>
                        <div class="col-md-4">
                            {{ form.password2|addatr:"class: form-control, id:password2" }}
                            {% if form.password2.errors %}
                                {% for error in form.password2.errors %}
                                    <div class="invalid-feedback invalid-feedback-custom">{{ error }}</div>
                                {% endfor %}
                            {% endif %}
                        </div>
                    </div>
                    <div class="row">
                       <div class="col-md-7">
                            <div class="text-right">
                                <input type="submit" class="btn btn-outline-primary w-25" value="Utwórz konto">
                            </div>
                        </div>
                    </div>
                </form>
            {% endif %}
        </div>
    </div>
{% endblock %}

templates/users/reset_password_form.html
{% extends '../base.html' %}
{% load form_attrs %}

{% block main %}

    <hr class="hr-custom">

    <h2>Resetuj hasło</h2>
    <h5>Nie masz konta? <a href="{% url 'register' %}">Załóż nowe.</a></h5>

    <hr class="hr-custom">

    <div class="row">
        <div class="col-md-12">
            {% if form %}
                <form method="POST">
                    {% csrf_token %}
                    <div class="form-group row">
                        <label for="email" class="col-md-3 col-form-label">Email*:</label>
                        <div class="col-md-4"> {{ form.email|addatr:"class: form-control, id:email" }}</div>
                    </div>
                    <div class="row">
                       <div class="col-md-7">
                            <div class="text-right">
                                <input type="submit" class="btn btn-outline-primary w-25" value="Resetuj hasło">
                            </div>
                        </div>
                    </div>
                </form>
            {% endif %}
        </div>
    </div>
{% endblock %}

templates/users/reset_password_update.html
{% extends '../base.html' %}
{% load form_attrs %}

{% block main %}

    <hr class="hr-custom">

    <h2>Resetuj hasło</h2>

    <hr class="hr-custom">

    <div class="row">
        <div class="col-md-12">
            {% if form %}
                <form method="POST">
                    {% csrf_token %}
                    <div class="form-group row">
                        <label for="password" class="col-md-3 col-form-label">Podaj nowe hasło*:</label>
                        <div class="col-md-4"> {{ form.password|addatr:"class: form-control, id:password" }}</div>
                    </div>
                    <div class="form-group row">
                        <label for="password2" class="col-md-3 col-form-label">Powtórz nowe hasło*:</label>
                        <div class="col-md-4"> {{ form.password2|addatr:"class: form-control, id:password2" }}</div>
                    </div>
                    <div class="row">
                       <div class="col-md-7">
                            <div class="text-right">
                                <input type="submit" class="btn btn-outline-primary w-25" value="Zmień hasło">
                            </div>
                        </div>
                    </div>
                </form>
            {% endif %}
        </div>
    </div>
{% endblock %}

templates/users/user_detail.html
{% extends '../base.html' %}

{% block main %}

	<hr class="hr-custom">

	<div class="row">
		<div class="col-md-8 mx-auto">
			<h2 class="featurette-heading">Witaj {{ object.get_short_name }}!</h2>
			<h4>Tu znajdziesz informacje o swoim postępie z loboratorium oraz dane osobiste</h4>
		</div>
	</div>

	<hr class="hr-custom">

	<h3>Twoje zaliczenia laboratorii</h3>
	<div class="row">
		<div class="col-md-12">
			{% if courses %}
				{% for course in courses %}
					<h3>{{ course.course.name }} <small>( {{ course.get_user_points }}/{{ course.course.get_max_points }} pkt.)</small></h3>		
					<table class="table table-sm table-hover table-responsive">
					  <thead>
					    <tr>
					      <th scope="col">#</th>
					      <th scope="col">Laboratorium</th>
					      <th scope="col">Status zadania</th>
					      <th scope="col">Punkty</th>
					      <th scope="col">Zadanie domowe</th>
					      <th scope="col">Ostatnia modyfikacja</th>
					      <th scope="col">Przesłano</th>
					    </tr>
					  </thead>
					  <tbody>
				  		{% for lecture in course.lectures_in_course.all %}				
						    <tr>
						      <th scope="row">{{ forloop.counter }}</th>
						      <td>{{ lecture.lecture.name }}</td>
						      <td>{{ lecture.get_status_display }}</td>
						      <td>{% if lecture.get_status_display == "Przesłano" %}&#8212;&#8212;{% else %}{{ lecture.points }}{% endif %}</td>
						      <td>
						      	<a href="{% url 'task' lecture.lecture.course.slug lecture.lecture.slug %}">{{ lecture.get_task.get_status_display|default:"Oczekuje" }}</a>
						      </td>
						      <td>{{ lecture.updated|date:"d.m.y H:i" }}</td>
						      <td>{{ lecture.created|date:"d.m.y H:i" }}</td>
						    </tr>
					    {% endfor %}
					  </tbody>
					</table>
				{% endfor %}
			{% else %}
				<h4 class="text-center text-muted">Brak akcji do wyświetlenia</h4>
			{% endif %}
		</div>
	</div>

	<hr class="hr-custom">

	<div class="row">
		<div class="col-md-12">
			<h2>
				<span>Twoje dane osobiste</span>
				<a href="{% url 'profile-edit' %}">
					<button type="button" class="btn btn-sm btn-outline-info">edytuj</button>
				</a>
			</h2>
			<div class="row">
				<div class="col-md-4">
					<div class="rounded-circle profile-circle mx-auto">
						<div class="profile-circle-text"> {{ object.get_short_name|first }}</div>
					</div>
				</div>
				<div class="col-5 m-auto pt-4">
					<div class="row">
						<div class="col-6"><strong>imie</strong></div>
						<div class="col-6">{{ object.first_name }}</div>
					</div>
					<div class="row">
						<div class="col-6"><strong>naziwsko</strong></div>
						<div class="col-6">{{ object.last_name }}</div>
					</div>
					<div class="row">
						<div class="col-6"><strong>email</strong></div>
						<div class="col-6">{{ object.email }}</div>
					</div>
					<div class="row">
						<div class="col-6"><strong>numer indeksu</strong></div>
						<div class="col-6">{{ object.index|default:"&#8212;&#8212;&#8212;&#8212;" }}</div>
					</div>
					<div class="row">
						<div class="col-6"><strong>grupa dziekańska</strong></div>
						<div class="col-6">{{ object.group|default:"&#8212;&#8212;&#8212;&#8212;" }}</div>
					</div>
				</div>
			</div>
		</div>
	</div>

{% endblock %}